import 'package:flutter_application_1/models/veiculos.dart';

final List<Veiculo> veiculosList = [
  Veiculo(
    id: 1,
    marca: 'Fiat',
    modelo: 'Uno',
    placa: 'ABC1234',
    ano: '2020',
    capacidade: 5,
    imageUrl: 'assets/images/uno.png',
  ),
  Veiculo(
    id: 2,
    marca: 'Fiat',
    modelo: 'Palio',
    placa: 'DEF5678',
    ano: '2021',
    capacidade: 5,
    imageUrl: 'assets/images/palio.png',
  ),
  Veiculo(
    id: 3,
    marca: 'Fiat',
    modelo: 'Mobi',
    placa: 'GHI9012',
    ano: '2022',
    capacidade: 5,
    imageUrl: 'assets/images/mobi.png',
  ),
  Veiculo(
    id: 4,
    marca: 'Ford',
    modelo: 'Mustang',
    placa: 'JKL3456',
    ano: '2020',
    capacidade: 4,
    imageUrl: 'assets/images/mustang.png',
  ),
  Veiculo(
    id: 5,
    marca: 'Toyota',
    modelo: 'Corolla',
    placa: 'MNO7890',
    ano: '2021',
    capacidade: 5,
    imageUrl: 'assets/images/corolla.png',
  ),
  Veiculo(
    id: 6,
    marca: 'Ferrari',
    modelo: 'F40',
    placa: 'PQR1234',
    ano: '2021',
    capacidade: 2,
    imageUrl: 'assets/images/f40.png',
  ),
];
