import 'package:flutter_application_1/database/pessoas.dart';
import 'package:flutter_application_1/database/veiculos.dart';
import 'package:flutter_application_1/models/viagens.dart';

List<Trip> viagensList = [
  Trip(
    veiculo: veiculosList[0],
    estadoOrigem: "RS",
    cidadeOrigem: 'Erechim',
    estadoDestino: "RS",
    cidadeDestino: 'Porto Alegre',
    startDate: DateTime(2023, 9, 16, 10, 30),
    dataFim: DateTime(2023, 9, 17, 14, 30),
    responsavel: pessoasList[0],
    participantes: [pessoasList[0]],
  ),
  Trip(
    veiculo: veiculosList[1],
    estadoOrigem: "RS",
    cidadeOrigem: 'Erechim',
    estadoDestino: "RS",
    cidadeDestino: 'Gaurama',
    startDate: DateTime(2023, 9, 17, 10, 30),
    dataFim: DateTime(2023, 9, 18, 14, 30),
    responsavel: pessoasList[1],
    participantes: [pessoasList[1], pessoasList[0]],
  ),
  Trip(
    veiculo: veiculosList[2],
    estadoOrigem: "RS",
    cidadeOrigem: 'Erechim',
    estadoDestino: "RS",
    cidadeDestino: 'Porto Alegre',
    startDate: DateTime(2023, 9, 18, 14, 30),
    dataFim: DateTime(2023, 9, 19, 14, 30),
    responsavel: pessoasList[2],
    participantes: [pessoasList[2]],
  ),
  Trip(
    veiculo: veiculosList[3],
    estadoOrigem: "RS",
    cidadeOrigem: 'Erechim',
    estadoDestino: "RS",
    cidadeDestino: 'Viadutos',
    startDate: DateTime(2023, 9, 19, 14, 30),
    dataFim: DateTime(2023, 9, 20, 14, 30),
    responsavel: pessoasList[2],
    participantes: [pessoasList[2], pessoasList[1]],
  ),
  Trip(
    veiculo: veiculosList[4],
    estadoOrigem: "RS",
    cidadeOrigem: 'Erechim',
    estadoDestino: "RS",
    cidadeDestino: 'Porto Alegre',
    startDate: DateTime(2023, 9, 20, 14, 30),
    dataFim: DateTime(2023, 9, 21, 14, 30),
    responsavel: pessoasList[1],
    participantes: [pessoasList[1], pessoasList[0], pessoasList[2]],
  ),
  Trip(
    veiculo: veiculosList[5],
    estadoOrigem: "RS",
    cidadeOrigem: 'Erechim',
    estadoDestino: "RS",
    cidadeDestino: 'Porto Alegre',
    startDate: DateTime(2023, 9, 20, 14, 30),
    dataFim: DateTime(2023, 9, 21, 14, 30),
    responsavel: pessoasList[0],
    participantes: [pessoasList[0], pessoasList[1]],
  ),
];
