import 'package:flutter_application_1/database/pessoas.dart';
import 'package:flutter_application_1/database/veiculos.dart';
import 'package:flutter_application_1/models/viagens.dart';

List<Trip> viagensList = [
  Trip(
    vehicle: veiculosList[0],
    originState: "RS",
    originCity: 'Erechim',
    destinationState: "RS",
    destinationCity: 'Porto Alegre',
    startDate: DateTime(2023, 9, 16, 10, 30),
    endDate: DateTime(2023, 9, 17, 14, 30),
    responsavel: pessoasList[0],
    participantes: [pessoasList[0]],
  ),
  Trip(
    vehicle: veiculosList[1],
    originState: "RS",
    originCity: 'Erechim',
    destinationState: "RS",
    destinationCity: 'Gaurama',
    startDate: DateTime(2023, 9, 17, 10, 30),
    endDate: DateTime(2023, 9, 18, 14, 30),
    responsavel: pessoasList[1],
    participantes: [pessoasList[1], pessoasList[0]],
  ),
  Trip(
    vehicle: veiculosList[2],
    originState: "RS",
    originCity: 'Erechim',
    destinationState: "RS",
    destinationCity: 'Porto Alegre',
    startDate: DateTime(2023, 9, 18, 14, 30),
    endDate: DateTime(2023, 9, 19, 14, 30),
    responsavel: pessoasList[2],
    participantes: [pessoasList[2]],
  ),
  Trip(
    vehicle: veiculosList[3],
    originState: "RS",
    originCity: 'Erechim',
    destinationState: "RS",
    destinationCity: 'Viadutos',
    startDate: DateTime(2023, 9, 19, 14, 30),
    endDate: DateTime(2023, 9, 20, 14, 30),
    responsavel: pessoasList[2],
    participantes: [pessoasList[2], pessoasList[1]],
  ),
  Trip(
    vehicle: veiculosList[4],
    originState: "RS",
    originCity: 'Erechim',
    destinationState: "RS",
    destinationCity: 'Porto Alegre',
    startDate: DateTime(2023, 9, 20, 14, 30),
    endDate: DateTime(2023, 9, 21, 14, 30),
    responsavel: pessoasList[1],
    participantes: [pessoasList[1], pessoasList[0], pessoasList[2]],
  ),
  Trip(
    vehicle: veiculosList[5],
    originState: "RS",
    originCity: 'Erechim',
    destinationState: "RS",
    destinationCity: 'Porto Alegre',
    startDate: DateTime(2023, 9, 20, 14, 30),
    endDate: DateTime(2023, 9, 21, 14, 30),
    responsavel: pessoasList[0],
    participantes: [pessoasList[0], pessoasList[1]],
  ),
];
