name: flutter_application_1
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  intl: ^0.18.1
  http: ^0.13.4
  image_picker: ^1.0.4
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
